### PR TITLE
feat: output tag name and upload url

### PR DESCRIPTION
**Pull request by mmarchini**
The tag name is useful to interact with the release on following steps,
and the upload url is useful to upload assets to the release.

Fix: https://github.com/GoogleCloudPlatform/release-please-action/issues/8
Fix: https://github.com/GoogleCloudPlatform/release-please-action/issues/41

### CODE REVIEW

**Comment by bcoe** [comment]
@mmarchini thank you for the contribution 👌

**Comment by bcoe** [comment]
@mmarchini tagged release@1.4.0

**Comment by jef** [comment]
what does `tag_name` and `upload_url` look like? we can update some doc around the change. thanks for putting this out!

**Comment by mmarchini** [comment]
Both are equal to their respective values in the [Create Release API response](https://developer.github.com/v3/repos/releases/#response-4). The `tag_name` is the tag name (not to be mistaken with the release name), and the upload_url is an URL to the [upload asset API endpoint](https://developer.github.com/v3/repos/releases/#upload-a-release-asset). Agreed we should add some documentation, maybe an extra section in the readme with all values set in the output of the action.

**Pull request merged**
